name: "Comment a Plan on a PR"

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: "Terraform CDK Diff"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Install dependencies
        run: yarn install
      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v0.1.0
        with:
          terraformVersion: 1.0.7
          cdktfVersion: 0.11.1
          stackName: my-stack
          mode: plan-only
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
